### ISSUE TITLE
Storage of noise value in chrom structure

### ISSUE THREAD

**Issue by tjschuckrug** [MrFuppes/IDL_IAU_Chrom#1]
In def_ref_structs.pro, line 76, noise is initialised as a float array of length 20. call_noisecalc.pro in line 50 fills one element of this array. Only the element corresponding to the selected quantifier is filled. 

Why is noise an array? This does not really make sense given that height and area are initialized as one-dimensional floats.

It's a bit nasty in the end, because to extract the noise, you first need to check at which index of the array it is stored by evaluating the selected quantifier (or doing some other magic on that array).

**Comment by FObersteiner** [comment]
Looking back to the time I introduced this, it is kind of a prototyping residual. As you can guess, making it an array had the intention to hold a noise value for each quantifier m/q. That's not consistent with area/height and the size of 20 elements is arbitrary.

For consistency and to avoid some pitfalls of asynchronous programming, I would nowadays make it a scalar as you suggest. So feel free to branch a version with that change; we can then merge that into the master after it has been tested.
